name: rp2 port

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [PICO]
    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1.3.0
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - name: Initialize lv_bindings submodule
      run: git submodule update --init --recursive lib/lv_bindings  
    - name: Initialize Micropython submodules
      run: make -C ports/rp2 BOARD=${{ matrix.board }} USER_C_MODULES=../../lib/lv_bindings/bindings.cmake submodules
    - name: Build mpy-cross
      run: make -j $(nproc) -C mpy-cross
    - name: Build ${{ matrix.board }}
      run: make -j $(nproc) -C ports/rp2 BOARD=${{ matrix.board }} USER_C_MODULES=../../lib/lv_bindings/bindings.cmake
    - uses: actions/upload-artifact@v2
      if: ${{ env.GITHUB_EVENT_NAME }} == 'push'
      with:
        name: ${{ matrix.board }}.hex
        path: ports/rp2/build-${{ matrix.board }}/firmware.elf
